filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/ssh_logs.log
  fields:
    log_type: ssh_honeypot
    service: ssh-honeypot
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /logs/apparmor_audit.log
  fields:
    log_type: apparmor
    service: apparmor
  fields_under_root: true

# Disable ILM and use simple index management
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "ssh-honeypot"
setup.template.pattern: "ssh-honeypot-*"
setup.dashboards.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "ssh-honeypot-logs"

setup.kibana:
  host: "kibana:5601"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - dissect:
      tokenizer: "%{timestamp} [[%{event_type}]] [%{source}] %{details}"
      field: "message"
      target_prefix: "parsed"
  - rename:
      fields:
        - from: "parsed.timestamp"
          to: "event_timestamp"
        - from: "parsed.event_type"
          to: "event_type"
        - from: "parsed.source"
          to: "source_component"
        - from: "parsed.details"
          to: "event_details"
      ignore_missing: true