FROM python:3.13-slim

WORKDIR /app

RUN mkdir -p logs

COPY main.py .
COPY logs_writter.py .
COPY seccomp_filter.py .
COPY capture_apparmor_events.py .

RUN pip install paramiko

EXPOSE 2222

CMD ["python", "main.py"]
